apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skool-mvp-ingress
  namespace: argocd
  labels:
    app: skool-mvp-ingress
spec:
  project: default
  source:
    repoURL: https://github.com/hcuri/skool-mvp-gitops.git
    targetRevision: main
    path: environments/dev/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

