replicaCount: 2

image:
  repository: hcuri/skool-mvp-api
  tag: de86fdb
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

env:
  logLevel: info
  databaseSecretName: skool-mvp-db

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 128Mi
